import ProfileNavbar from "@/components/nav/ProfileNavbar";
import type { Metadata } from "next";
import { Nunito } from "next/font/google";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "motorfy.lk",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className={`${nunito.className} bg-slate-100 flex flex-row`}>
      <ProfileNavbar />
      {children}
    </main>
  );
}
